### ISSUE TITLE
Problems about the results of the simulator

### ISSUE THREAD

**Issue by ChaiHuichao** [Amit-P89/-DRackSim#2]
Hi, I've been doing some work on building simulations of distributed memory systems, and I found your work to be excellent. However, I encountered two small problems in reproducing your work (referring to the cycle-based model). I look forward to communicating with you to see if you have any suggestions.
    The first question is about multi-core setups. In mem_defs.cpp, set num_nodes and num_mem_pools = 1, and core_count = 4 to simulate the four-core configuration of a single node. Run the "OMP_NUM_THREADS=4 ../../.. /pin -t obj-intel64/Ins_Tracer.so -N 1 --. /workloads/XSBench -s small -t 4 &," command to use the XSBench as workload. However, in the simulation result, only core 0 is working, the other three cores are not assigned any instruction. After checking the intermediate results, I found that the thread IDs are all 0. But I'm I didn't modify Benchmark, nor did I modify your ins_trace.cpp, so what could be the problem?
    The second problem may be more troublesome. I tried different loads, such as XSBench, HPCG and Redis database, but the memory usage in the result statistics file "mem_stats" is very small. For example, set the local memory:remote memory to 1: 1, and both to be 4GB, the values of Local Memory Used and Remote Memory Used in the result are both about 0.001 GB. Maybe the memory usage is too small, when I tested the impact of bandwidth in inter_connect.cpp on system performance, setting it to 100/400Gbps and 1/4Gbps had almost no impact on system performance, which is very unusual. I guess it could be that the memory usage in the stats is too small to make the system performance insensitive to bandwidth. I would like to ask you what could be the cause of this low memory usage?
    I look forward to your response. Any advice would be of great help to me. Thank you!

**Comment by Amit-P89** [comment]
@ChaiHuichao thanks for your kind words about this work. 

I understand why you are getting only thread with only core-0 is working. By default the following script will start profiling the workload from the start itself.
OMP_NUM_THREADS=4 ../../.. /pin -t obj-intel64/Ins_Tracer.so -N 1 --. /workloads/XSBench -s small -t 4 &

and most workloads have a significantly large initial single threaded part before it start  spanning more threads.

If you want to directly skip to the multithreaded part, just add a knob -T 1 in the command as following: 

OMP_NUM_THREADS=4 ../../.. /pin -t obj-intel64/Ins_Tracer.so -N 1 -T 1 --. /workloads/XSBench -s small -t 4 &

The second issue regarding the mem_stats will be solved once the simulation is running for good number of instructions say "100M" instructions. That will create a significantly good difference in the memory usage. And the thing that you were simulating the initial single-threaded part for all the workloads, the memory consumption and the number of memory requests are not high, as you also pointed that out.

If you want to try out new workloads, I can suggest some which will allocate a large amount of memory in short time.

https://www.nas.nasa.gov/software/npb.html
you can try openmp versions of mg, ft with class C or above from this benchmark suite.  With this, you will be able to see good difference in performance with small number of instructions. 

I hope this will solve both the issues.

**Comment by ChaiHuichao** [comment]
Thanks for your reply, with your help the first problem about multi-core simulation has been solved, now the Simulator can do single node quad-core emulation normally ^_^.
But the second issue about memory usage is still a bit problematic. I tried to run 5e7 instructions under XSBench workload with single node quad-core, and I got the final mem_stat test result with only 0.065GB memory used. If it's convenient can you share your mem_stat and node_result results to help me compare and see what's wrong?
One trend I noticed in my testing is that the more instructions are executed, the slower the increase in memory usage is. That is, the number of instructions and memory accesses printed out per epoch increases linearly, but the memory usage increase turns out to be slower and slower (specifically the first epoch has 11MB of mem used in the result, and at the end of the run for the 120th epoch it only increases to 60MB), is there a problem with this?
I also tried the MG.C workload at your suggestion, and running 1e7 instructions, the memory use was also only 4MB, so I have a feeling if there is a problem with the information in trace file generated by the Pintools, or if some hyperparameters are not defined correctly in the Simulator?
Also a small question, as I understand it in this current simulator architecture, does nic bandwidth and switch bandwidth defined in interconnect.cpp only affect the latency of accessing remote memory?
Thank you again for your previous response and I look forward to receiving your further suggestions!

**Comment by Amit-P89** [comment]
@ChaiHuichao good to know that the first issue is solved.

> I tried to run 5e7 instructions under XSBench workload with single node quad-core, and I got the final mem_stat test result with only 0.065GB memory used.

I guess this is not incorrect for 50M instructions, XSBench will allocate only this amount of memory (0.065GB = 66.56MB). The memory allocation is totally dependent on the workload. A new page is allocated in memory only if there is a new page address that is observed in the instruction trace. Some workloads expand very fast in memory, others take some time and some of them allocate very less memory. 

I had added the results for MG.C after ist epoch in the below link, which is 50M simulation cycles (ist result cycle). 
https://shorturl.at/mtCGL

You can see, it has allocated good amount of memory at 50:50 ratio in local/remote. For correct simulation results, you should manually close the process running in the background (workload) and then clear all shared memory variables using clear_sm.sh before you start the next simulation with the same node number. (This part is yet to be automated through the code.) You can follow this issue for more details on it : https://github.com/Amit-P89/-DRackSim/issues/1

Yes, NIC and switch bandwidth will affect the remote memory latency as it will increase the transmission delay component.

Feel free to ask about any other issue that you face.

**Comment by Amit-P89** [comment]
@ChaiHuichao Please close if the issue is solved.

**Comment by ChaiHuichao** [comment]
Thanks for the reply, I'm still working on the low memory usage of the simulator these days, but with your help I think I've pinpointed the problem.
Also I have a small question, does the current simulator structure only simulate the memory usage increase and not include the memory release function? If I want to add the memory release feature, does the existing trace structure already contain the address and size information of the memory release? Or do I need to modify the ins_trace file to get the information about memory release?

**Comment by Amit-P89** [comment]
Ok, no problem.

Yes, Currently, it just counts the memory usage by the program. The memory release in real machine is a policy decision which is performed by the operating system's memory manager through garbage collectors and silently evicting cold memory pages. 
On the other hand, memory allocation is forceful when a new address is referenced by the CPU. 
Deallocation can be easily implemented following some memory eviction algorithm. You can start with **mmap.cpp** if you want to implement it. 

ins_trace file will have nothing to do with memory release functions. Although you can get some information through the pintool about the memory pages that are deallocated in your machine on which you are running your workload. But then, our simulated machine is different from that machine and we do not want to implement the same behavior, rather follow some standard algorithms to perform activities like deallocation.

**Comment by ChaiHuichao** [comment]
Thank you for your reply, it really helped me a lot and I have solved most of my problems.

**Comment by Amit-P89** [comment]
@ChaiHuichao thats great. You are welcome.
