### ISSUE TITLE
Turn on log memory_access_completion_log.trc

### ISSUE THREAD

**Issue by jakzy** [Amit-P89/-DRackSim#3]
Hi! 
Currently studying your tool in order to understand if it can be used for my tasks. I've got some results and found a message  in _memory_access_completion_log.trc_

> Log Turned Off, Un-comment log statements in mem_defs.h read and write complete functions to turn it on

I wanted to turn that log on, but didn't find that header. After that I found stated functions in _mem_defs.cpp_ but changing them gave no result but active prints in terminal.

How can I turn log on at _memory_access_completion_log.trc_ then?

Thank you!

**Comment by Amit-P89** [comment]
Hi, Thanks for using this tool. 

I added some code to produce a more detailed memory request log to make it easy for analyses. Please clone a new copy and use it. You can turn the log on/off by using the macro #define MEM_LOG in the "main.cpp".

Regards.

**Comment by jakzy** [comment]
Thank you
